### ISSUE TITLE
Error: Invalid Authentication Ticket

### ISSUE THREAD

**Issue by Inhibitus0** [ic3w0lf22/Roblox-Account-Manager#418] opened 2024-07-17 00:18 UTC
I can't join any game using any of my accounts as this error appears every time, removing and adding the accounts again doesnt fix it.
![paining](https://github.com/user-attachments/assets/73008ec4-c8f3-417f-a6ba-3af1a7c08e63)

**Comment by mungislolkl** [comment] 2024-07-17 00:36
same thing, tried on different devices but still the same problem and after re-adding the account it launches it only once and then problem repeats. Probably some dumb ass roblox update

**Comment by atkzth** [comment] 2024-07-17 01:07
same

**Comment by trainStation31** [comment] 2024-07-17 14:47
same

**Comment by fricco** [comment] 2024-07-17 14:55
Started happening today. Removing and adding the accounts didn't work. Neither using the "Get Authentication Ticket"

**Comment by Dekamelot** [comment] 2024-07-17 15:58
bro what the hell

**Comment by L444SIN** [comment] 2024-07-17 21:28
@fricco @Dekamelot @atkzth @mungislolkl @Inhibitus0 
![image_2024-07-17_172812504](https://github.com/user-attachments/assets/93655380-7066-4467-9730-470df652c3ea)

yo a solution I used for this issue was literally using the "open browser" feature instead of just clicking the join server so you have to manually join the game yourself from account managers roblox website

**Comment by blakopitchy** [comment] 2024-07-17 22:30
> @fricco @Dekamelot @atkzth @mungislolkl @Inhibitus0 ![image_2024-07-17_172812504](https://private-user-images.githubusercontent.com/175893363/349689341-93655380-7066-4467-9730-470df652c3ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTU2MzgsIm5iZiI6MTcyMTI1NTMzOCwicGF0aCI6Ii8xNzU4OTMzNjMvMzQ5Njg5MzQxLTkzNjU1MzgwLTcwNjYtNDQ2Ny05NzMwLTQ3MGRmNjUyYzNlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMjI4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmJhNGRiMzgzOTg0M2Q3Yzc0ZmZhNzY0MTNlN2RiODE5OTMxNmQxNTMwNTllOTk5ZjQ4MWY0NjhjZGI1OGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d_OW1EgETKoJBJIXBHb58YJZz7BllCrmPEm25FCGX44)
> 
> yo a solution I used for this issue was literally using the "open browser" feature instead of just clicking the join server so you have to manually join the game yourself from account managers roblox website hope this helps

Will they fix the issue? I tried doing the browser thing but it wouldn’t let me join my account it kicked my main and my alt stayed even tho my thing is on multi account thingy I also can’t play with several accounts becuase of this thing that happened will it get fixed?

**Comment by Inhibitus0** [comment] 2024-07-17 22:37
> > @fricco @Dekamelot @atkzth @mungislolkl @Inhibitus0 ![image_2024-07-17_172812504](https://private-user-images.githubusercontent.com/175893363/349689341-93655380-7066-4467-9730-470df652c3ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTU2MzgsIm5iZiI6MTcyMTI1NTMzOCwicGF0aCI6Ii8xNzU4OTMzNjMvMzQ5Njg5MzQxLTkzNjU1MzgwLTcwNjYtNDQ2Ny05NzMwLTQ3MGRmNjUyYzNlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMjI4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmJhNGRiMzgzOTg0M2Q3Yzc0ZmZhNzY0MTNlN2RiODE5OTMxNmQxNTMwNTllOTk5ZjQ4MWY0NjhjZGI1OGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d_OW1EgETKoJBJIXBHb58YJZz7BllCrmPEm25FCGX44)
> > yo a solution I used for this issue was literally using the "open browser" feature instead of just clicking the join server so you have to manually join the game yourself from account managers roblox website hope this helps
> 
> Will they fix the issue? I tried doing the browser thing but it wouldn’t let me join my account it kicked my main and my alt stayed even tho my thing is on multi account thingy I also can’t play with several accounts becuase of this thing that happened will it get fixed?

Idk if it will get fixed or not but the browser thing works for me

**Comment by TezHD** [comment] 2024-07-17 22:55
Idk if this is happening for everyone but it looks like it's happening for most people, but yea the open browser method works but it's slow.

**Comment by TimLiz** [comment] 2024-07-17 23:04
Can reproduce, we need someone to make pull request to add `Content-Type: application/json` header into `https://auth.roblox.com/v1/authentication-ticket/` request, its update in Roblox API.

**Comment by olivausf** [comment] 2024-07-17 23:06
> @fricco @Dekamelot @atkzth @mungislolkl @Inhibitus0 ![image_2024-07-17_172812504](https://private-user-images.githubusercontent.com/175893363/349689341-93655380-7066-4467-9730-470df652c3ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTc4MTksIm5iZiI6MTcyMTI1NzUxOSwicGF0aCI6Ii8xNzU4OTMzNjMvMzQ5Njg5MzQxLTkzNjU1MzgwLTcwNjYtNDQ2Ny05NzMwLTQ3MGRmNjUyYzNlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMzA1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2VjZDY1N2RlZDc3ZDg5MzgyNDAwNTQ4NDFmODY0OWY2ZjUwNTM5NjFhMTJiYzA0ZTNlMmExOGYwMDljM2Q4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jg9_L_w0vb4lX0iR2IMnodSlnfFDh8yVKbFXB945WwQ)
> 
> yo a solution I used for this issue was literally using the "open browser" feature instead of just clicking the join server so you have to manually join the game yourself from account managers roblox website hope this helps

Is there a trick to this? Tried opening multiple accounts and keeps closing the prior game instances. Appreciate any help!

**Comment by TheMix00** [comment] 2024-07-17 23:25
> I can't join any game using any of my accounts as this error appears every time, removing and adding the accounts again doesnt fix it. ![paining](https://private-user-images.githubusercontent.com/175761079/349311074-73008ec4-c8f3-417f-a6ba-3af1a7c08e63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTkwMDUsIm5iZiI6MTcyMTI1ODcwNSwicGF0aCI6Ii8xNzU3NjEwNzkvMzQ5MzExMDc0LTczMDA4ZWM0LWM4ZjMtNDE3Zi1hNmJhLTNhZjFhN2MwOGU2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMzI1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGQ0NjM2NjIwYTMzNjQ1NzQ3MDU3ZTkyYjlkNjdjNzE2OWE2ZDkyMmExYjRhOTlkNGYxZjBlYTkyYzQyNTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I-xg3v8jy0VJC9xTTrz6ohxJtZWSnSr3z_I0W6AfgQE)

i have same issue is there any way to fix ?

**Comment by TimLiz** [comment] 2024-07-17 23:54
Made pull request to fix it, you can download my fork and compile by urself

**Closed** 2024-07-18 11:26 UTC
